<h1 style="color: white; 
    font-size: 46px; 
    text-align: center; 
    background: #00ccff; 
    padding: 30px; 
    ">Quality Report</h1>

In [1]:
#!pip install tensorflow==2.3.1

import tensorflow as tf
print('tensorflow == ', tf.__version__)
import numpy as np

tensorflow ==  2.3.1


In [2]:
#!pip install tensorflow_datasets

import tensorflow_datasets as tfds

In [3]:
from model_image import ModelImage
from functionality import FunctionalityAnalysis

Using TensorFlow backend.


# Image Binary Classification Model

In [4]:
model_path ='./saved_model/image-binary-classification-cats-vs-dogs'
data_tf = 'cats_vs_dogs'

In [5]:
model = ModelImage()
model.load_model(model_path = model_path)
model.load_data(data_tf = data_tf, test_samples=10)
y_pred, y_true = model.predict()

Model loaded! Input shape: (None, 224, 224, 3) , number of classes: 1
Data loaded!  <PrefetchDataset shapes: ((None, 224, 224, 3), (None,)), types: (tf.float32, tf.int64)>


In [6]:
analysis = FunctionalityAnalysis(y_true, y_pred, 'classification', 'binary')
analysis.evaluate_performance()

Confusion Matrix: 
 [[3 0]
 [0 7]] 

Accuracy:   1.0 

Precision:  1.0
Recall:     1.0
F1 Score:   1.0


# Image Multiclass Classification Model

### - TF dataset

In [7]:
model_path ='./saved_model/image-multiclass-mnist-no-robust'
data_tf = 'mnist'

In [8]:
model = ModelImage()
model.load_model(model_path = model_path)
model.load_data(data_tf=data_tf, test_samples=10)
y_pred, y_true = model.predict()

Model loaded! Input shape: (None, 28, 28, 1) , number of classes: 10
Data loaded!  <PrefetchDataset shapes: ((None, 28, 28, 1), (None,)), types: (tf.float32, tf.int64)>


In [9]:
analysis = FunctionalityAnalysis(y_true, y_pred, 'classification', 'multiclass')
analysis.evaluate_performance()

Confusion Matrix: 
 [[1 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1]] 

Accuracy:   1.0 



### - Dataset from directory

In [10]:
model_path = './saved_model/saved_model/flower_photos'
data_path = './datasets/flower_photos'

In [11]:
model = ModelImage()
model.load_model(model_path = model_path)
model.load_data(data_dir = data_path, split = 0.01)
y_pred, y_true = model.predict()

Model loaded! Input shape: (None, 180, 180, 3) , number of classes: 5
Found 3670 files belonging to 5 classes.
Using 100 files for validation.
Data loaded!  <PrefetchDataset shapes: ((None, 180, 180, 3), (None,)), types: (tf.float32, tf.int32)>


In [12]:
analysis = FunctionalityAnalysis(y_true, y_pred, 'classification', 'multiclass')
analysis.evaluate_performance()

Confusion Matrix: 
 [[11  6  0  2  0]
 [ 0 18  1  4  0]
 [ 2  2 11  1  5]
 [ 0  0  1 15  0]
 [ 0  1  4  4 12]] 

Accuracy:   0.67 

